language: python
python: 
  - "3.6"
services:
  - postgresql
env:
  - SECRET_KEY="FOO" DATABASE_URL="sqlite:///:memory:" ALLOWED_HOSTS="*"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - python manage.py migrate
script:
  - coverage run --source=. manage.py test
after_success:
  - coveralls
