language: python
python: 
  - "3.6"
services:
  - postgresql
env:
  - SECRET_KEY=FOO
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python manage.py migrate
script:
  - coverage run --source=. manage.py test
after_success:
  - coveralls
