language: python
python: 
  - "3.6"
services:
  - postgresql
env:
  - SECRET_KEY="FOO" DATABASE_URL="sqlite:////:memory:" DEBUG="True"
install:
  - pip install -r platform/base-requirements.txt
  - pip install coveralls
before_script:
  - python manage.py migrate
script:
  - coverage run --source=. manage.py test
after_success:
  - coveralls
