version: '3'

services:
  djworkplace_redis:
    container_name: djworkplace_redis
    image: redis:alpine
  
  djworkplace_app:
    container_name: djworkplace_app
    build: 
      context: .
      dockerfile: platform/dockerfile
    volumes:
      - .:/code
    depends_on:
      - djworkplace_redis

  djworkplace_celery:
    container_name: djworkplace_celery
    build: 
      context: .
      dockerfile: platform/dockerfile
    command: celery -A djworkplace worker -l info
    environment:
      - SECRET_KEY=testing_secret_key
    volumes:
      - .:/code
    depends_on:
      - djworkplace_redis
