version: '3'

services:
  db:
    container_name: db
    image: postgres
  app:
    container_name: app
    build: 
      context: platform/
      dockerfile: app-dockerfile
    volumes:
      - .:/code
    depends_on:
      - db