version: '3'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: platform/base-dockerfile
    image: djworkplace/base:1
    environment:
      - SECRET_KEY=testing_secret_key
      - ALLOWED_HOSTS=
    volumes:
      - .:/code