version: '3'

services:
  djworkplace_redis:
    container_name: djworkplace_redis
    image: redis
  djworkplace_app:
    container_name: djworkplace_app
    build: 
      context: .
      dockerfile: platform/dockerfile
    environment:
      - SECRET_KEY=testing_secret_key
      - ALLOWED_HOSTS=localhost
      - DEFAULT_ADMIN_USERNAME=admin
      - DEFAULT_ADMIN_EMAIL=admin@example.com
      - DEFAULT_ADMIN_PASSWORD=admin
      - COMPANY_NAME=djWorkplace
    volumes:
      - .:/code
    depends_on:
      - djworkplace_redis
