version: '3'

services:
  djworkplace_app:
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=sqlite:////code/db.sqlite3
      - DEBUG=True