version: '3'

services:
  db:
    container_name: db
    image: postgres
  app:
    container_name: app
    build: 
      context: platform/
      dockerfile: app-dockerfile
    command: uwsgi --ini /code/platform/djworkplace-uwsgi.ini
    volumes:
      - .:/code
    ports:
      - "3031:3031"
    depends_on:
      - db
    environment:
      - STATIC_ROOT=/static
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ${PWD}/platform/djworkplace-nginx.conf:/etc/nginx/conf.d/djworkplace-nginx.conf