version: '3'

services:
  djworkplace_db:
    container_name: djworkplace_db
    image: postgres

  djworkplace_app:
    command: uwsgi --socket :3031 --chdir /code/ --wsgi-file djworkplace/wsgi.py --master --processes 2 --threads 2
    ports:
      - "3031:3031"
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
    depends_on:
      - djworkplace_db

  djworkplace_nginx:
    container_name: djworkplace_nginx
    image: nginx
    depends_on:
      - djworkplace_app
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ${PWD}/platform/djworkplace-nginx.conf:/etc/nginx/conf.d/djworkplace-nginx.conf