version: '3'

services:
  djworkplace_app:
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "80:80"
    environment:
      - "DEBUG=True"
      - "EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend"
  djworkplace_celery:
    environment:
      - "DEBUG=True"
      - "EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend"
