# Generated by Django 2.1.7 on 2019-03-24 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='holiday_approvals', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
    ]
