# Generated by Django 2.2 on 2019-05-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_auto_20190324_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='approval_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
