# Generated by Django 2.1.7 on 2019-03-16 19:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('holidays', '0002_auto_20190316_1942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HolidayPeriod',
            new_name='Holiday',
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['start', 'end'], 'verbose_name': 'holdays', 'verbose_name_plural': 'holidays'},
        ),
    ]
