# Generated by Django 2.1.7 on 2019-03-16 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_auto_20190316_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['start', 'end'], 'verbose_name': 'holidays', 'verbose_name_plural': 'holidays'},
        ),
        migrations.AlterField(
            model_name='holiday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
