# Generated by Django 2.1.7 on 2019-03-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0004_auto_20190316_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['-start', '-end'], 'verbose_name': 'holidays', 'verbose_name_plural': 'holidays'},
        ),
    ]
