# Generated by Django 2.2.2 on 2019-06-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_birthday'),
        ('holidays', '0005_publicholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicholiday',
            name='location',
        ),
        migrations.AddField(
            model_name='publicholiday',
            name='locations',
            field=models.ManyToManyField(related_name='local_holidays', to='staff.Location', verbose_name='locations'),
        ),
    ]
