# Generated by Django 2.2.2 on 2019-07-07 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0006_auto_20190627_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 7, 20, 32, 33, 200225, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacation',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
