# Generated by Django 2.2.1 on 2019-08-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0008_auto_20190803_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
