# Generated by Django 2.2.1 on 2019-08-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0009_leave_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-start', '-end'], 'verbose_name': 'leave', 'verbose_name_plural': 'leaves'},
        ),
    ]
