# Generated by Django 2.2.4 on 2019-08-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20190805_0756'),
        ('holidays', '0012_auto_20190803_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(help_text='Yearly permission days for this type', verbose_name='days')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_limits', to='staff.Department', verbose_name='department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_limits', to='staff.Location', verbose_name='location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_leaves', to='holidays.LeaveType', verbose_name='type')),
            ],
            options={
                'verbose_name': 'leave limit',
                'verbose_name_plural': 'leave limits',
                'ordering': ['department', 'location'],
                'unique_together': {('department', 'location', 'type')},
            },
        ),
    ]
