# Generated by Django 2.2.4 on 2019-12-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    def set_leave_year(apps, schema_editor):
        Leave = apps.get_model('holidays', 'Leave')
        Leave.objects.all().update(year=2019)

    def remove_leave_year(apps, schema_editor):
        LeaveType = apps.get_model('holidays', 'Leave')
        Leave.objects.all().update(year=None)


    dependencies = [
        ('holidays', '0014_auto_20191210_2040'),
    ]

    operations = [
        migrations.RunPython(set_leave_year, remove_leave_year),
    ]
