# Generated by Django 2.2.4 on 2019-12-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0015_auto_20191210_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
