# Generated by Django 2.1.7 on 2019-03-18 23:21

from django.db import migrations
from django.contrib.auth import get_user_model
from django.conf import settings

class Migration(migrations.Migration):

    def create_default_admin(apps, schema_editor):
        get_user_model().objects.create_superuser(
            settings.DEFAULT_ADMIN_USERNAME, 
            settings.DEFAULT_ADMIN_EMAIL, 
            settings.DEFAULT_ADMIN_PASSWORD 
        )


    def remove_default_admin(apps, schema_editor):
        get_user_model().objects.filter(username=os.environ.get('DEFAULT_ADMIN_USERNAME', Migration.DEFAULT_ADMIN_USERNAME)).delete()

    dependencies = [
        ('staff', '0006_staffprofile_birthday'),
    ]

    operations = [
        migrations.RunPython(create_default_admin, remove_default_admin)
    ]