# Generated by Django 2.1.7 on 2019-03-18 23:21

from django.db import migrations
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib.auth.hashers import make_password


class Migration(migrations.Migration):

    def create_default_admin(apps, schema_editor):

        User = apps.get_model('auth', 'User')
        User.objects.create(
           username=settings.DEFAULT_ADMIN_USERNAME, 
           email=settings.DEFAULT_ADMIN_EMAIL, 
           password=make_password(settings.DEFAULT_ADMIN_PASSWORD),
           is_staff=True,
           is_superuser=True
        )
        

    def remove_default_admin(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        User.objects.filter(username=os.environ.get('DEFAULT_ADMIN_USERNAME', Migration.DEFAULT_ADMIN_USERNAME)).delete()

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_admin, remove_default_admin)
    ]