# Generated by Django 2.1.7 on 2019-03-16 17:42

from django.db import migrations
from django.contrib.auth import get_user_model
import os

class Migration(migrations.Migration):

    DEFAULT_ADMIN_USERNAME = 'admin'
    DEFAULT_ADMIN_EMAIL = 'admin@example.com'
    DEFAULT_ADMIN_PASSWORD = 'admin'

    def create_default_admin(apps, schema_editor):
        get_user_model().objects.create_superuser(
            os.environ.get('DEFAULT_ADMIN_USERNAME', Migration.DEFAULT_ADMIN_USERNAME), 
            os.environ.get('DEFAULT_ADMIN_EMAIL', Migration.DEFAULT_ADMIN_EMAIL), 
            os.environ.get('DEFAULT_ADMIN_PASSWORD', Migration.DEFAULT_ADMIN_PASSWORD), 
        )


    def remove_default_admin(apps, schema_editor):
        get_user_model().objects.filter(username=os.environ.get('DEFAULT_ADMIN_USERNAME', Migration.DEFAULT_ADMIN_USERNAME)).delete()

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_admin, remove_default_admin)
    ]


