# Generated by Django 2.2.2 on 2019-06-27 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190318_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staff.staffprofile',),
        ),
    ]
