# Generated by Django 2.1.7 on 2019-03-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190318_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='holidays',
            field=models.PositiveSmallIntegerField(default=0, help_text='Yearly holidays', verbose_name='holidays'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='personal_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Yearly personal days', verbose_name='personal days'),
            preserve_default=False,
        ),
    ]
