# Generated by Django 2.1.7 on 2019-03-23 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0003_auto_20190320_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='managers'),
        ),
    ]
