# Generated by Django 2.2 on 2019-05-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_department_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='holidays',
        ),
        migrations.AddField(
            model_name='department',
            name='vacations',
            field=models.PositiveSmallIntegerField(default=20, help_text='Yearly vacation days', verbose_name='vacations'),
            preserve_default=False,
        ),
    ]
