# Generated by Django 2.2.2 on 2019-06-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20190507_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
    ]
